# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jmiguel-nitro/Documents/cpp/fireC

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jmiguel-nitro/Documents/cpp/fireC

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jmiguel-nitro/Documents/cpp/fireC/CMakeFiles /home/jmiguel-nitro/Documents/cpp/fireC//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jmiguel-nitro/Documents/cpp/fireC/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named breakB

# Build rule for target.
breakB: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 breakB
.PHONY : breakB

# fast build rule for target.
breakB/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/breakB.dir/build.make CMakeFiles/breakB.dir/build
.PHONY : breakB/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/breakB.dir/build.make CMakeFiles/breakB.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/breakB.dir/build.make CMakeFiles/breakB.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/breakB.dir/build.make CMakeFiles/breakB.dir/main.cpp.s
.PHONY : main.cpp.s

src/ball.o: src/ball.cpp.o
.PHONY : src/ball.o

# target to build an object file
src/ball.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/breakB.dir/build.make CMakeFiles/breakB.dir/src/ball.cpp.o
.PHONY : src/ball.cpp.o

src/ball.i: src/ball.cpp.i
.PHONY : src/ball.i

# target to preprocess a source file
src/ball.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/breakB.dir/build.make CMakeFiles/breakB.dir/src/ball.cpp.i
.PHONY : src/ball.cpp.i

src/ball.s: src/ball.cpp.s
.PHONY : src/ball.s

# target to generate assembly for a file
src/ball.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/breakB.dir/build.make CMakeFiles/breakB.dir/src/ball.cpp.s
.PHONY : src/ball.cpp.s

src/brick.o: src/brick.cpp.o
.PHONY : src/brick.o

# target to build an object file
src/brick.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/breakB.dir/build.make CMakeFiles/breakB.dir/src/brick.cpp.o
.PHONY : src/brick.cpp.o

src/brick.i: src/brick.cpp.i
.PHONY : src/brick.i

# target to preprocess a source file
src/brick.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/breakB.dir/build.make CMakeFiles/breakB.dir/src/brick.cpp.i
.PHONY : src/brick.cpp.i

src/brick.s: src/brick.cpp.s
.PHONY : src/brick.s

# target to generate assembly for a file
src/brick.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/breakB.dir/build.make CMakeFiles/breakB.dir/src/brick.cpp.s
.PHONY : src/brick.cpp.s

src/paddle.o: src/paddle.cpp.o
.PHONY : src/paddle.o

# target to build an object file
src/paddle.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/breakB.dir/build.make CMakeFiles/breakB.dir/src/paddle.cpp.o
.PHONY : src/paddle.cpp.o

src/paddle.i: src/paddle.cpp.i
.PHONY : src/paddle.i

# target to preprocess a source file
src/paddle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/breakB.dir/build.make CMakeFiles/breakB.dir/src/paddle.cpp.i
.PHONY : src/paddle.cpp.i

src/paddle.s: src/paddle.cpp.s
.PHONY : src/paddle.s

# target to generate assembly for a file
src/paddle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/breakB.dir/build.make CMakeFiles/breakB.dir/src/paddle.cpp.s
.PHONY : src/paddle.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... breakB"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/ball.o"
	@echo "... src/ball.i"
	@echo "... src/ball.s"
	@echo "... src/brick.o"
	@echo "... src/brick.i"
	@echo "... src/brick.s"
	@echo "... src/paddle.o"
	@echo "... src/paddle.i"
	@echo "... src/paddle.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

